using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace PhoneBook.AutoGenerated
{
    [Keyless]
    [Table("phones")]
    public partial class Phone
    {
        [Column("phone_id")]
        public int PhoneId { get; set; }
        [Required]
        [Column("phone_name")]
        [StringLength(250)]
        public string PhoneName { get; set; }
        [Required]
        [Column("phone_number")]
        [StringLength(250)]
        public string PhoneNumber { get; set; }
    }
}
